blank_issues_enabled: false
contact_links:
  - name: üí¨ Installation instructions / –ò–Ω—Å—Ç—Ä—É–∫—Ü–∏—è –ø–æ —É—Å—Ç–∞–Ω–æ–≤–∫–µ 
    url: https://github.com/remittor/zapret-openwrt/wiki/Installing-zapret%E2%80%90openwrt-package
    about: Installation instructions / –ò–Ω—Å—Ç—Ä—É–∫—Ü–∏—è –ø–æ —É—Å—Ç–∞–Ω–æ–≤–∫–µ

  - name: üìö Original documetation / –û—Ä–∏–≥–∏–Ω–∞–ª—å–Ω–∞—è –¥–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è –∫ zapret'—É
    url: https://github.com/bol-van/zapret/blob/master/docs/readme.md
    about: README zapret
